### ISSUE TITLE
feature of adversarial nodes

### ISSUE THREAD

**Issue by ScottLiao920** [Nanyuu/TUA#1]
hi Nanyuu, this work is very exciting. I've read your paper on it, but I am still confused about the node feature of the adversarial nodes. In ur paper algo.1 (page 4), a certain node feature of the selected node is set to 1 while you are performing experiments on citation datasets, in which the node feature should be the degree of this node. So is the feature of adversarial nodes still 1s and 0s while appending to the benign graphs or they're either scaled or appended to normalized graphs?

**Comment by Nanyuu** [comment]
Hi ScottLiao920,
Thanks for the question.

For the given datasets (Cora, Citeseer), the features of each node are one-hot encoded. So, the features of Fake Node (Adversarial Node) in **Cora**, for example, should also be a vector like [1x1433] (i.e. one row in feature matrix **X^'**).

At the beginning of attack, the fake features are initialized to 0s (zero vector). To perform the attack, the Adversarial Node is treated as ordinary nodes, which means that it should be normalized if necessary. After picking a certain feature in fake features, it will be set to 1.

Then, in the next iteration, the normalization (both the original nodes and adversarial node) should be done all over again. This part is integrated in **Algorithm.1** (first line in the **For-Loop**).

I hope this will clear up your confusion. Thank again for this question. Let me know if you have more questions.

-----edit----
Among the benchmark datasets, PubMed is not one-hot encoded in the experiment. The problem of unmatched declaration of feature matrix (X) and the dataset PubMed will be fixed in paper.
